var barrgedate=[
    {
        time:4,
        username:"雪豹",
        text:"嗷呜~"
    },
    {
        time:0.5,
        username:"小马珍珠",
        text:"但是珍珠没有了"
    },
    {
        time:1,
        username:"丁真",
        text:"一眼丁真鉴定为纯纯的好活"
    },
    {
        time:2,
        username:"柯洁",
        text:"1！5！"
    },
    {
        time:4,
        username:"雪豹",
        text:"嗷呜~"
    },
    {
        time:4,
        username:"雪豹",
        text:"嗷呜~"
    }
];